version: "3"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
     - "5672:5672"
     - "15672:15672"
  mssql:
    container_name: dev-mssql
    hostname: mssql
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
     - "5680:1433"
    environment:
      SA_PASSWORD: "S_1234567890"
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"